---
project_dir: ~/Project
downloads_dir: ~/Downloads

downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_osx: yes
configure_extra: yes
configure_dock: yes
configure_zsh: yes

dotfiles_repo: https://github.com/flemzord/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .gitignore
  - .osx
  - .vimrc

homebrew_taps:
  - homebrew/cask
  - wallix/awless
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - aws/tap
  - lucagrulla/tap

homebrew_installed_packages:
  - autoconf
  - automake
  - bash-completion
  - git
  - go
  - gpg
  - nvm
  - ssh-copy-id
  - wget
  - curl
  - htop
  - kubernetes-cli
  - kubernetes-helm
  - mas
  - ncdu
  - packer
  - scw
  - terraform
  - zsh
  - tree
  - dockutil
  - watch
  - zplug
  - fzf
  - awscli
  - httpie
  - jq
  - terminal-notifier
  - vim
  - wget
  - glances
  - krew
  - rain

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - brave-browser
  - firefox
  - discord
  - iterm2
  - vlc
  - visual-studio-code
  - linear-linear
  - jetbrains-toolbox
  - lens
  - virtualbox
  - vagrant
  - deepl
  - messenger
  - bluejeans
  - zoomus
  - whatsapp
  - font-jetbrains-mono
  - font-source-code-pro
  - grammarly
  - postman
  - transmission
  - transmit
  - pocket-casts

# See `geerlingguy.mas` role documentation for usage instructions.
mas_signin_dialog: yes
mas_installed_apps:
  - { id: 747648890, name: "Telegram" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }
  - { id: 557168941, name: "Tweetbot for Twitter" }
  - { id: 784801555, name: "Microsoft OneNote" }
  - { id: 462054704, name: "Microsoft Word" }
  - { id: 462058435, name: "Microsoft Excel" }
  - { id: 462062816, name: "Microsoft Powerpoint" }
  - { id: 985367838, name: "Microsoft Outlook" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" } # RDP Client
  - { id: 803453959, name: "Slack" }
  - { id: 1176895641, name: "Spark – Email App by Readdle" }
  - { id: 1333542190, name: "1Password 7 - Password Manager" }
  - { id: 1475387142, name: "Tailscale" }
  - { id: 1284863847, name: "Unsplash Wallpapers" }

mas_upgrade_all_apps: yes

osx_script: "~/.osx --no-restart"

dockitems_disabled:
  - Launchpad
  - Siri
  - Mail
  - Safari
  - Contacts
  - Notes
  - Rappels
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Calendrier
  - Terminal
  - Plans
  - Pages
  - Numbers
  - Keynote
  - Préférences Système

dockitems_enabled:
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 1
  - name: Tweetbot
    path: "/Applications/Tweetbot.app"
    pos: 3
  - name: Telegram
    path: "/Applications/Telegram.app"
    pos: 4
